# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autoupdate_commit_msg: "chore(tooling): Update pre-commit hooks"
  autofix_commit_msg: |
    chore(lint): Add auto fixes from pre-commit hooks

    For more information, see https://pre-commit.ci

exclude: ^dist/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: pretty-format-json
        args:
          - --autofix
        exclude: package-lock.json
      - id: trailing-whitespace
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args:
          - --branch=main

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.20.0
    hooks:
      - id: markdownlint-cli2
        name: lint markdown files
        args:
          - --fix

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.36.1
    hooks:
      - id: check-github-workflows
        name: validate workflow files

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.10
    hooks:
      - id: actionlint
        name: lint workflow files

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        name: run shellcheck
        args: ["-x"]

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
      - id: shfmt-src
        name: run shfmt
