name: "Test Workflow with Local Dive Action"
on: [push]

jobs:
  sample-workflow:
    runs-on: ubuntu-latest
    name: Analyze image efficiency using Dive
    steps:
      - name: Checkout repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Analyze image efficiency
        uses: ./
        with:
          image: "node:alpine"
          config: ${{ github.workspace }}/.dive-ci
          exit-zero: "false"
