name: "Test Workflow with Local Dive Action"
on: [push]

jobs:
  sample-workflow:
    runs-on: ubuntu-latest
    name: Analyze image efficiency using Dive
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Analyze image efficiency
        uses: ./
        with:
          image: "node:alpine"
          config: ${{ github.workspace }}/.dive-ci
          exit-zero: "false"
