name: "Test Workflow with Local Dive Action"
on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  validate-dist:
    name: Validate dist is up to date
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ secrets.MARTHA_TOKEN }}
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: "24"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Commit and push dist if changed
        run: |
          git config user.name "Martha Prime"
          git config user.email "martha-prime@primeft.com"
          git add dist/
          git diff --staged --quiet || (git commit -m "chore: Update dist" && git push)

  sample-workflow:
    name: Analyze image efficiency using Dive
    runs-on: ubuntu-latest
    needs: validate-dist
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Analyze image efficiency
        uses: ./
        with:
          image: "node:alpine"
          config: ${{ github.workspace }}/.dive-ci
          exit-zero: "false"
